create table HrAtrition (
    Age INT,
    Attrition TEXT,
    BusinessTravel TEXT,
    DailyRate INT,
    Department TEXT,
    DistanceFromHome INT,
    Education INT,
    EducationField TEXT,
    EmployeeCount TEXT,  -- Duplicate column name handled
    EmployeeNumber TEXT,
    EnvironmentSatisfaction INT,
    Gender TEXT,
    HourlyRate INT,
    JobInvolvement INT,
    JobLevel INT,
    JobRole TEXT,
    JobSatisfaction INT,
    MaritalStatus TEXT,
    MonthlyIncome NUMERIC(12,2),
    MonthlyRate INT,
    NumCompaniesWorked INT,
    Over18 TEXT,
    OverTime TEXT,
    PercentSalaryHike INT,
    PerformanceRating INT,
    RelationshipSatisfaction INT,
    StandardHours INT,
    StockOptionLevel INT,
    TotalWorkingYears INT,
    TrainingTimesLastYear INT,
    WorkLifeBalance INT,
    YearsAtCompany INT,
    YearsInCurrentRole INT,
    YearsSinceLastPromotion INT,
    YearsWithCurrManager INT
);
